### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by mottosso** [richardlayman/feather#7]
I think it would be a good idea to get Travis-ci setup to run automated builds for us.

If you're unfamiliar; it'll basically trigger a build for every push we, or anyone else makes to ensure it builds without failing. If it fails, it'll tell us in the pull-request.

We can also set it up to run tests and things, but this is a good first step.

I'll send a request for this now as well, in case you wonder what that's all about. I think it needs approval from an organisation owner, as opposed to just a member (like me).

**Comment by richardlayman** [comment]
Sorry about being late on this issue, I got busy yesterday and wasn't able to get to it. This weekend I'm going to check this out. I've never heard of Travis and wanted to learn more about it before I commented on it.

**Comment by mottosso** [comment]
No worries, it's important you feel comfortable with it as well.

I'd also like to set us up with AppVeyor; which is the Windows-equivalent. Bottom line, it'll make our collaboration, and Feather as a whole, a lot easier to work with and a lot more stable. Especially when more people start to chime in.

**Comment by richardlayman** [comment]
>I'd also like to set us up with AppVeyor; which is the Windows-equivalent.

If it doesn't effect me, you're free to do as you see fit when it comes to Windows.

**Comment by richardlayman** [comment]
This has been accepted. I won't be integrated till later but it will be done before v0.1 release

**Comment by mottosso** [comment]
> If it doesn't effect me, you're free to do as you see fit when it comes to Windows.

This will affect you. For the better, or at least that's the idea.

To elaborate; the practice I've got in mind with Travis and AppVeyor for Feather is called "continuous integration". I'm not sure you are familiar with it, but in a nutshell, it means Feather will automatically get built by a remote computer for every push anyone makes and that the results of that build are then reflected in the pull-request thread. The end result is that you'll be able to tell whether a change broke something.

Add to this that you can start adding "[badges][1]" to the README that also reflects the current state of the project, based on these automatic builds.

[1]: http://shields.io/

The immediate benefit is that code that breaks anything become immediately apparent; not just on your own platform, but on any supported platform. Travis and AppVeyor can perform builds simultaneously on lots of platforms under lots of circumstances, such as with different versions of GCC or Boost on different OSs and processor architectures.

Another benefit is automatic deployment. Each build can trigger the creation of an installer, for any platform, and upload it to the right place without the user having to do anything. That means that even a new contributor can add to Feather and have a new installer created for every supported platform, without knowing anything about deployment. Just the code that he writes. His code will get run through the same series of tests as anyone such that the created builds and installers are always functional.

Once you've been down the path of continuous integration, you won't want to go back. :)

I'll set this up and you can remove it if it isn't something you want.

But it needs admin access to add.

Can you go here and activate it, or give me admin access to feather3d so I can manage it and AppVeyor?

- https://travis-ci.org/profile/feather3d

**Comment by richardlayman** [comment]
>This will affect you. For the better, or at least that's the idea.

What I meant to say was that if it's something that deals with Windows and won't affect the main code, then I'm not really worried about it.

>But it needs admin access to add.

Gave both apps permission last night.

>Can you go here and activate it, or give me admin access to feather3d so I can manage it and AppVeyor?

Done.

**Comment by mottosso** [comment]
> What I meant to say was that if it's something that deals with Windows and won't affect the main code, then I'm not really worried about it.

Cool. There will likely be things needed for Windows to play ball, right? For example we can't use Posix-only libraries, in the same spirit as we can't use Windows-only libraries. But I wouldn't expect these things to affect the program as a whole.

> Gave both apps permission last night.

Yeah, they both now have access to the organisation, but we'll need to add the individual project(s) as well, and it takes someone within the organisation with admin access to do that.

Have a look at the link, you might have to sign up. Otherwise, I'll need admin access, if only for the time it takes to get set-up.

**Comment by richardlayman** [comment]
Travis has been added but could not find the AppVeyor service in the Webhooks/Service page. Do I need to add you as well or is this good enough?

**Comment by mottosso** [comment]
Looks good, will have a look at setting things up in a few days time. I'm heading out on a project for the next two weeks and will not be around as much during that time, but will keep up to date on issues and pull requests.

**Comment by richardlayman** [comment]
Ok, good luck on your project. Thanks for all your help!

**Comment by mottosso** [comment]
Thanks and don't mention it. I like where it's going and enjoy being part of it. :)
